name: axoproject
description: A new Flutter project.
publish_to: 'none'
version: 4.05.080+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^4.2.0
  get: ^4.6.5
  flutter_svg: ^1.1.3
  shared_preferences: ^2.0.15
  http: ^0.13.5
  barcode: ^2.2.3
  barcode_widget: ^2.0.3
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.11
  gallery_saver: ^2.3.2
  permission_handler: ^10.0.0
  intl: ^0.18.0
  encrypt: ^5.0.1
  sizer: ^2.0.15
  sqflite: ^2.0.3+1
  auto_size_text: ^3.0.0
  open_filex: ^4.3.2
  share_plus: ^7.2.1
  internet_connection_checker: ^1.0.0+1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.5
  image_picker: ^0.8.6+1
  scan: ^1.6.0
  pdf: ^3.9.0
  printing: ^5.10.4
  flutter_pdfview: ^1.2.5
  device_info_plus: ^8.1.0
  # syncfusion_flutter_barcodes: ^21.1.35
  dropdown_button2: ^1.7.1
  getwidget: ^3.0.1
  url_launcher: ^6.1.10
  shimmer: ^2.0.0
  rename: ^2.1.1
  geolocator: ^9.0.2
  flutter_slidable: ^2.0.0
  syncfusion_flutter_charts: ^20.3.47
  uuid: ^3.0.7
  webview_flutter: ^3.0.4
  google_maps_flutter: ^2.2.1
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils_plus: ^2.0.2
  blue_thermal_printer: ^1.2.3
  # flutter_native_html_to_pdf: ^1.0.1
  image: ^4.1.3
  location: ^5.0.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/drawer/
    - assets/print_templates/
    - assets/print_templates/order_template/
    - assets/print_templates/report_templates/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
